spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:mongo}

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/biblioteca_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:12345}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  data:
    mongodb:
      # Azure usará su variable, localmente usa tu Cluster0
      uri: ${SPRING_DATA_MONGODB_URI:mongodb+srv://castillejoangulo:Vien2023@cluster0.0cw5yye.mongodb.net/?appName=Cluster0}
      database: biblioteca_db

server:
  # Azure inyecta 'PORT', si no existe usa 8080 (estándar Spring)
  port: ${PORT:8080}
  ssl:
    # IMPORTANTE: En Azure debe ser 'false' para que no pida el .p12
    enabled: ${SSL_ENABLED:false}
    key-store: classpath:library-key.p12
    key-store-password: "123456"
    key-store-type: PKCS12
    key-alias: library