spring:
  profiles:
    active: mongo

---
spring:
  config:
    activate:
      on-profile: mongo
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      database: biblioteca_db
  # Forzar la exclusión también desde propiedades por si acaso
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

server:
  port: ${PORT:80}